parameters:
- name: serviceConnection
  type: string

steps:
- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@2
  displayName: 'Install Power Platform Build Tools'

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.whoami.PowerPlatformWhoAmi@2
  name: "whoami"
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: '${{parameters.serviceConnection}}'

- powershell: |  
    #$microsoftXrmDataPowerShellModule = '$(CoETools_Microsoft_Xrm_Data_PowerShell)'
    #Import-Module $microsoftXrmDataPowerShellModule
    #$conn = Get-CrmConnection -ConnectionString "$(CdsBaseConnectionString)${{parameters.serviceConnection}}"
    ## Get the Environment name (which is a GUID)
    #$environmentId = $conn.EnvironmentId
    Write-Host "EnvironmentId - $(BuildTools.EnvironmentId)"
    # Set the EnvironmentId as a global variable for use in other templates
    echo "##vso[task.setvariable variable=EnvironmentId]$(BuildTools.EnvironmentId)"
  displayName: 'Set EnvironmentId'